// Identity, intro and self-contained recovery-code checks. All company writes use the local mock.
const { chromium } = require('playwright');
const { start } = require('./sheetmock');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
start(0, async ({ srv, db, url }) => {
  let browser, checks = 0;
  const ok = (name, value) => { assert.ok(value, name); checks++; console.log('  ok   ' + name); };
  const join = async (page, name) => { await page.goto(url + 'index.html?dev'); await page.click('#intro'); await page.fill('#nm', name); await page.click('#go'); await page.waitForFunction(() => MUSTEAT.state.id); };
  try {
    browser = await chromium.launch();
    const a = await browser.newContext({ viewport: { width: 1000, height: 850 } });
    const b = await browser.newContext({ viewport: { width: 1000, height: 850 } });
    const errors = []; [a, b].forEach(c => c.on('page', p => p.on('pageerror', e => errors.push(e.message))));
    const A = await a.newPage(), B = await b.newPage();
    await join(A, 'Luke 🥡'); await join(B, 'Second Browser');
    const aid = await A.evaluate(() => MUSTEAT.state.id), bid = await B.evaluate(() => MUSTEAT.state.id);
    ok('separate browser profiles get distinct invisible IDs', aid !== bid && /^p[0-9a-f]{32}$/.test(aid));
    await A.reload();
    ok('returning to the same browser resumes the same ID', await A.evaluate(() => MUSTEAT.state.id) === aid);
    ok('the company is shared while personal saves differ', db.players.some(p => p.id === aid) && db.players.some(p => p.id === bid));
    const draw = async random => A.evaluate(value => { const original = Math.random; try { Math.random = () => value; MUSTEAT.state.ration = 0; MUSTEAT.state.rationDue = 0; MUSTEAT.claimRation(); return MUSTEAT.state.rationDue - MUSTEAT.state.ration; } finally { Math.random = original; } }, random);
    ok('ration cooldown minimum is three minutes', await draw(0) === 3 * 60000);
    ok('ration cooldown maximum is fifteen minutes', await draw(0.999999) === 15 * 60000);
    const rationDue = await A.evaluate(() => MUSTEAT.state.rationDue);
    ok('ration cannot be claimed again during the cooldown', await A.evaluate(() => { const before = MUSTEAT.state.cash; MUSTEAT.claimRation(); return MUSTEAT.state.cash === before; }));
    await A.reload();
    ok('ration countdown survives reload without rerolling', await A.evaluate(() => MUSTEAT.state.rationDue) === rationDue);
    ok('old 20-hour waits migrate and overdue rations become ready', await A.evaluate(() => { const s = MUSTEAT.state; s.ration = Date.now() - 7 * 3600000; delete s.rationDue; MUSTEAT.render(); const first = s.rationDue; MUSTEAT.render(); return first === s.rationDue && first < Date.now() && !!document.querySelector('[data-act="ration"]'); }));
    ok('saved hour-long deadlines shorten once from the last claim', await A.evaluate(() => { const s = MUSTEAT.state; s.ration = Date.now() - 20 * 60000; s.rationDue = s.ration + 4 * 3600000; MUSTEAT.render(); const first = s.rationDue, wait = first - s.ration; MUSTEAT.render(); return first === s.rationDue && wait >= 3 * 60000 && wait <= 15 * 60000 && !!document.querySelector('[data-act="ration"]'); }));
    await A.click('[data-act="ration"]');
    await A.click('[data-act="replayIntro"]');
    ok('intro keeps six lines, now set in 2099', await A.locator('#intro .lines p').count() === 6 && /2099/.test(await A.textContent('#intro')) && !/3019/.test(await A.textContent('#intro')) && /ACCESS DENIED/.test(await A.textContent('#intro')));
    await A.waitForTimeout(5500);
    ok('replayed intro stays open until the player continues', await A.isVisible('#intro') && await A.locator('#introContinue').textContent() === 'Click to continue');
    await A.keyboard.press('Enter');
    ok('keyboard continues without registering again', !await A.isVisible('#intro') && await A.evaluate(() => MUSTEAT.state.id) === aid && !await A.isVisible('#modal'));
    await A.click('[data-act="replayIntro"]'); await A.click('#intro');
    ok('clicking anywhere also continues the replayed intro', !await A.isVisible('#intro') && !await A.isVisible('#modal'));
    await A.click('[data-act="saveInfo"]');
    ok('save panel identifies the loaded citizen', (await A.textContent('#modalBox')).includes(aid) && /Luke/.test(await A.textContent('#modalBox')));
    await A.click('#ok');

    await A.evaluate(() => {
      const s = MUSTEAT.state;
      s.cash = 12000; s.total = 54000; s.gear = { trainers: 12, hover: 4 }; s.upg = { trainers1: true }; s.shop = { name: 'Airlock Café 🥡', at: Date.now() };
      s.played = 600; s.pace = { 1: 100, 10: 54000 }; s.dispatch = { done: 3, active: { start: s.deliveries, quota: 200, reward: 500, name: 'Feed Bunker 12' } };
      s.told = { gang: Date.now(), rec: Date.now() }; s.nextEvent = Date.now() + 1e9; s.crateAt = Date.now() + 1e9;
      s.log = [];
      MUSTEAT.save();
    });
    const code = await A.evaluate(() => { const s = JSON.parse(JSON.stringify(MUSTEAT.state)); s.log = [{ t: Date.now(), text: '<img src=x onerror="window.__pwned=1"><b>Good food</b>' }]; return MUSTEAT.encodeRecovery(s); });
    ok('code contains the whole compressed snapshot with a checksum', /^MUSTEAT1G\.[A-Za-z0-9_-]+\.[a-f0-9]{64}$/.test(code));
    const restored = await B.evaluate(code => MUSTEAT.decodeRecovery(code), code);
    ok('another browser decodes it without any cloud lookup', restored.id === aid && restored.cash === 12000 && restored.shop.name === 'Airlock Café 🥡' && restored.gear.hover === 4 && restored.upg.trainers1);
    ok('history and solo progression survive encoding', restored.pace[10] === 54000 && restored.dispatch.done === 3 && restored.dispatch.active.reward === 500);
    ok('recovery preserves the drawn ration deadline', restored.rationDue === await A.evaluate(() => MUSTEAT.state.rationDue));
    ok('imported log is safe text', !/<img|<b>/.test(restored.log[0].text) && /Good food/.test(restored.log[0].text));
    const broken = code.slice(0, -1) + (code.endsWith('0') ? '1' : '0');
    ok('damaged codes fail validation', await B.evaluate(async c => { try { await MUSTEAT.decodeRecovery(c); return false; } catch (e) { return /damaged/.test(e.message); } }, broken));
    ok('whitespace from a wrapped paste is accepted', (await B.evaluate(c => MUSTEAT.decodeRecovery(c), code.match(/.{1,80}/g).join('\n'))).id === aid);
    const plainCode = await A.evaluate(async () => { const compressor = window.CompressionStream; try { window.CompressionStream = undefined; return await MUSTEAT.encodeRecovery(MUSTEAT.state); } finally { window.CompressionStream = compressor; } });
    ok('uncompressed fallback restores in another browser', plainCode.startsWith('MUSTEAT1J.') && (await B.evaluate(c => MUSTEAT.decodeRecovery(c), plainCode)).id === aid);
    const badState = await A.evaluate(async () => { const s = JSON.parse(JSON.stringify(MUSTEAT.state)); s.cash = -1; return MUSTEAT.encodeRecovery(s); });
    ok('valid checksum cannot make invalid game data acceptable', await B.evaluate(async c => { try { await MUSTEAT.decodeRecovery(c); return false; } catch (e) { return /valid MustEat save/.test(e.message); } }, badState));
    // Stop the source so its old copy cannot continue syncing while we restore on the destination.
    await A.evaluate(() => { MUSTEAT.state.log = []; MUSTEAT.save(); });
    await A.close();
    await B.click('[data-act="saveInfo"]'); await B.click('[data-act="restoreCode"]');
    await B.fill('#recoveryIn', broken); await B.click('#readRecovery');
    await B.waitForFunction(() => /damaged/.test(document.getElementById('recoveryError').textContent));
    ok('failed restore leaves the existing save intact', await B.evaluate(() => MUSTEAT.state.id) === bid);
    await B.fill('#recoveryIn', code); await B.click('#readRecovery');
    await B.waitForSelector('#confirmRestore');
    ok('restore previews the citizen before replacing anything', /Resume Luke/.test(await B.textContent('#modalBox')) && await B.evaluate(() => MUSTEAT.state.id) === bid);
    await B.click('#confirmRestore');
    await B.waitForFunction(id => window.MUSTEAT && MUSTEAT.state.id === id, aid);
    ok('restored state survives navigation and its closing autosave', await B.evaluate(() => MUSTEAT.state.gear.hover === 4 && MUSTEAT.state.shop.name === 'Airlock Café 🥡'));
    ok('original browser save is retained as a local undo backup', await B.evaluate(() => JSON.parse(localStorage.musteat_save_before_restore).id) === bid);
    ok('hostile imported log did not execute', !await B.evaluate(() => window.__pwned || document.querySelector('#log img')));
    await B.evaluate(() => MUSTEAT.sync());
    ok('restore updates the original shared citizen rather than registering a duplicate', db.players.filter(p => p.id === aid).length === 1 && db.players.length === 2);
    await B.click('[data-act="saveInfo"]'); await B.click('[data-act="recoveryCode"]');
    await B.waitForFunction(() => document.getElementById('recoveryOut').value.startsWith('MUSTEAT1'));
    ok('recovery code is available through the user interface', (await B.inputValue('#recoveryOut')).length > 500 && !await B.locator('#copyRecovery').isDisabled());
    await B.click('#ok');
    await B.click('[data-act="saveInfo"]'); await B.click('[data-act="previousRecovery"]');
    await B.waitForSelector('#confirmRestore');
    ok('previous local save can be previewed for undo', /Second Browser/.test(await B.textContent('#modalBox')));
    await B.click('#cancel');
    await B.click('#reset'); await B.click('#confirm');
    await B.waitForSelector('#intro:not([hidden])');
    ok('reset no longer resurrects the old save on unload', await B.evaluate(() => !localStorage.getItem('musteat_save')));
    await B.goto(url + 'index.html?dev');
    await B.click('#intro');
    await B.click('[data-act="restoreCode"]'); await B.fill('#recoveryIn', code); await B.click('#readRecovery'); await B.waitForSelector('#confirmRestore'); await B.click('#confirmRestore');
    await B.waitForFunction(id => window.MUSTEAT && MUSTEAT.state.id === id, aid);
    ok('fresh browsers can restore before registering', await B.evaluate(() => MUSTEAT.state.id) === aid);

    const file = await b.newPage();
    await file.route('https://script.google.com/**', route => route.abort());
    await file.goto('file:///' + path.resolve(__dirname, '..', 'index.html').replace(/\\/g, '/') + '?dev');
    await file.click('#intro');
    ok('local file has a separate personal save from the hosted address', await file.evaluate(() => !MUSTEAT.state.id) && await file.isVisible('#nm'));
    await file.click('[data-act="restoreCode"]'); await file.fill('#recoveryIn', code); await file.click('#readRecovery');
    await file.waitForSelector('#confirmRestore');
    ok('recovery can be decoded directly from a file URL', /Resume Luke/.test(await file.textContent('#modalBox')));
    await file.close();
    const outDir = path.join(__dirname, '..', '.logs', 'recovery'); fs.mkdirSync(outDir, { recursive: true });
    await B.setViewportSize({ width: 360, height: 740 });
    await B.click('[data-act="replayIntro"]'); await B.waitForTimeout(3200);
    await B.screenshot({ path: path.join(outDir, 'intro-mobile.png') });
    ok('intro fits a phone screen', await B.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await B.click('#intro'); await B.click('[data-act="saveInfo"]');
    await B.screenshot({ path: path.join(outDir, 'save-panel-mobile.png') });
    ok('no browser errors', errors.length === 0);
    console.log(`\n${checks} recovery/identity checks passed.`);
  } catch (e) { console.error(e); process.exitCode = 1; }
  finally { if (browser) await browser.close(); srv.close(); }
});
